/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Title
 * Swagger Description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Address {
    'id'?: string;
    'userId'?: string;
    'title'?: string;
    'fullName'?: string;
    'phone'?: string;
    'country'?: string;
    'city'?: string;
    'district'?: string;
    'postalCode'?: string;
    'addressLine'?: string;
    'isInvoice'?: boolean;
    'isShipping'?: boolean;
    'createdAt'?: string;
}

