/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Title
 * Swagger Description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserType } from './user-type';

export interface RegisterInput {
    'email': string;
    'password': string;
    'firstName': string;
    'lastName': string;
    'phone': string;
    'userType': UserType;
    /**
     * Required if userType is CORPORATE
     */
    'companyName'?: string;
    /**
     * Required if userType is CORPORATE (10-11 digits)
     */
    'taxNumber'?: string;
    /**
     * Required if userType is CORPORATE
     */
    'taxOffice'?: string;
}



