/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Title
 * Swagger Description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserType } from './user-type';

export interface UpdateUserInput {
    'email'?: string;
    'firstName'?: string;
    'lastName'?: string;
    'phone'?: string;
    'userType'?: UserType;
    'companyName'?: string;
    'taxNumber'?: string;
    'taxOffice'?: string;
}



