/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Title
 * Swagger Description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { UserType } from './user-type';

export interface User {
    'id'?: string;
    'keycloakId'?: string;
    'email'?: string;
    'firstName'?: string | null;
    'lastName'?: string | null;
    'phone'?: string | null;
    'userType'?: UserType;
    'companyName'?: string | null;
    'taxNumber'?: string | null;
    'taxOffice'?: string | null;
    'addresses'?: Array<Address>;
    'createdAt'?: string;
    'updatedAt'?: string;
}



