/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Title
 * Swagger Description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AuthPasswordPutRequest } from '../interfaces';
// @ts-ignore
import type { AuthUpdatePutRequest } from '../interfaces';
// @ts-ignore
import type { AuthVerifyEmailPostRequest } from '../interfaces';
// @ts-ignore
import type { ErrorResponse } from '../interfaces';
// @ts-ignore
import type { LoginInput } from '../interfaces';
// @ts-ignore
import type { RegisterInput } from '../interfaces';
// @ts-ignore
import type { TokenResponse } from '../interfaces';
// @ts-ignore
import type { User } from '../interfaces';
/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Authenticates against Keycloak and returns JWT tokens.
         * @summary Login with email and password
         * @param {LoginInput} loginInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost: async (loginInput: LoginInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginInput' is not null or undefined
            assertParamExists('authLoginPost', 'loginInput', loginInput)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates the authenticated user\'s password in Keycloak
         * @summary Update user password
         * @param {AuthPasswordPutRequest} authPasswordPutRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authPasswordPut: async (authPasswordPutRequest: AuthPasswordPutRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authPasswordPutRequest' is not null or undefined
            assertParamExists('authPasswordPut', 'authPasswordPutRequest', authPasswordPutRequest)
            const localVarPath = `/auth/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authPasswordPutRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a user in Keycloak and saves profile to database. For CORPORATE users, companyName, taxNumber and taxOffice are required.
         * @summary Register a new user
         * @param {RegisterInput} registerInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost: async (registerInput: RegisterInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerInput' is not null or undefined
            assertParamExists('authRegisterPost', 'registerInput', registerInput)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates the authenticated user\'s profile in Postgres and Keycloak
         * @summary Update user profile
         * @param {AuthUpdatePutRequest} [authUpdatePutRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authUpdatePut: async (authUpdatePutRequest?: AuthUpdatePutRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authUpdatePutRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Activates user account in Postgres and Keycloak
         * @summary Verify email address via token link
         * @param {string} token Activation token sent to the user email
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyEmailGet: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('authVerifyEmailGet', 'token', token)
            const localVarPath = `/auth/verify-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Activates user account in Postgres and Keycloak
         * @summary Verify email address via token payload
         * @param {AuthVerifyEmailPostRequest} authVerifyEmailPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyEmailPost: async (authVerifyEmailPostRequest: AuthVerifyEmailPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authVerifyEmailPostRequest' is not null or undefined
            assertParamExists('authVerifyEmailPost', 'authVerifyEmailPostRequest', authVerifyEmailPostRequest)
            const localVarPath = `/auth/verify-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authVerifyEmailPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Authenticates against Keycloak and returns JWT tokens.
         * @summary Login with email and password
         * @param {LoginInput} loginInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLoginPost(loginInput: LoginInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLoginPost(loginInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates the authenticated user\'s password in Keycloak
         * @summary Update user password
         * @param {AuthPasswordPutRequest} authPasswordPutRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authPasswordPut(authPasswordPutRequest: AuthPasswordPutRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authPasswordPut(authPasswordPutRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authPasswordPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a user in Keycloak and saves profile to database. For CORPORATE users, companyName, taxNumber and taxOffice are required.
         * @summary Register a new user
         * @param {RegisterInput} registerInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRegisterPost(registerInput: RegisterInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRegisterPost(registerInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates the authenticated user\'s profile in Postgres and Keycloak
         * @summary Update user profile
         * @param {AuthUpdatePutRequest} [authUpdatePutRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authUpdatePut(authUpdatePutRequest?: AuthUpdatePutRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authUpdatePut(authUpdatePutRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authUpdatePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Activates user account in Postgres and Keycloak
         * @summary Verify email address via token link
         * @param {string} token Activation token sent to the user email
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authVerifyEmailGet(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authVerifyEmailGet(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authVerifyEmailGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Activates user account in Postgres and Keycloak
         * @summary Verify email address via token payload
         * @param {AuthVerifyEmailPostRequest} authVerifyEmailPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authVerifyEmailPost(authVerifyEmailPostRequest: AuthVerifyEmailPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authVerifyEmailPost(authVerifyEmailPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authVerifyEmailPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Authenticates against Keycloak and returns JWT tokens.
         * @summary Login with email and password
         * @param {AuthApiAuthLoginPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost(requestParameters: AuthApiAuthLoginPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse> {
            return localVarFp.authLoginPost(requestParameters.loginInput, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates the authenticated user\'s password in Keycloak
         * @summary Update user password
         * @param {AuthApiAuthPasswordPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authPasswordPut(requestParameters: AuthApiAuthPasswordPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authPasswordPut(requestParameters.authPasswordPutRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a user in Keycloak and saves profile to database. For CORPORATE users, companyName, taxNumber and taxOffice are required.
         * @summary Register a new user
         * @param {AuthApiAuthRegisterPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost(requestParameters: AuthApiAuthRegisterPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.authRegisterPost(requestParameters.registerInput, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates the authenticated user\'s profile in Postgres and Keycloak
         * @summary Update user profile
         * @param {AuthApiAuthUpdatePutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authUpdatePut(requestParameters: AuthApiAuthUpdatePutRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authUpdatePut(requestParameters.authUpdatePutRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Activates user account in Postgres and Keycloak
         * @summary Verify email address via token link
         * @param {AuthApiAuthVerifyEmailGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyEmailGet(requestParameters: AuthApiAuthVerifyEmailGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authVerifyEmailGet(requestParameters.token, options).then((request) => request(axios, basePath));
        },
        /**
         * Activates user account in Postgres and Keycloak
         * @summary Verify email address via token payload
         * @param {AuthApiAuthVerifyEmailPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyEmailPost(requestParameters: AuthApiAuthVerifyEmailPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authVerifyEmailPost(requestParameters.authVerifyEmailPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for authLoginPost operation in AuthApi.
 */
export interface AuthApiAuthLoginPostRequest {
    readonly loginInput: LoginInput
}

/**
 * Request parameters for authPasswordPut operation in AuthApi.
 */
export interface AuthApiAuthPasswordPutRequest {
    readonly authPasswordPutRequest: AuthPasswordPutRequest
}

/**
 * Request parameters for authRegisterPost operation in AuthApi.
 */
export interface AuthApiAuthRegisterPostRequest {
    readonly registerInput: RegisterInput
}

/**
 * Request parameters for authUpdatePut operation in AuthApi.
 */
export interface AuthApiAuthUpdatePutRequest {
    readonly authUpdatePutRequest?: AuthUpdatePutRequest
}

/**
 * Request parameters for authVerifyEmailGet operation in AuthApi.
 */
export interface AuthApiAuthVerifyEmailGetRequest {
    /**
     * Activation token sent to the user email
     */
    readonly token: string
}

/**
 * Request parameters for authVerifyEmailPost operation in AuthApi.
 */
export interface AuthApiAuthVerifyEmailPostRequest {
    readonly authVerifyEmailPostRequest: AuthVerifyEmailPostRequest
}

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * Authenticates against Keycloak and returns JWT tokens.
     * @summary Login with email and password
     * @param {AuthApiAuthLoginPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authLoginPost(requestParameters: AuthApiAuthLoginPostRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLoginPost(requestParameters.loginInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates the authenticated user\'s password in Keycloak
     * @summary Update user password
     * @param {AuthApiAuthPasswordPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authPasswordPut(requestParameters: AuthApiAuthPasswordPutRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authPasswordPut(requestParameters.authPasswordPutRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a user in Keycloak and saves profile to database. For CORPORATE users, companyName, taxNumber and taxOffice are required.
     * @summary Register a new user
     * @param {AuthApiAuthRegisterPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authRegisterPost(requestParameters: AuthApiAuthRegisterPostRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authRegisterPost(requestParameters.registerInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates the authenticated user\'s profile in Postgres and Keycloak
     * @summary Update user profile
     * @param {AuthApiAuthUpdatePutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authUpdatePut(requestParameters: AuthApiAuthUpdatePutRequest = {}, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authUpdatePut(requestParameters.authUpdatePutRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Activates user account in Postgres and Keycloak
     * @summary Verify email address via token link
     * @param {AuthApiAuthVerifyEmailGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authVerifyEmailGet(requestParameters: AuthApiAuthVerifyEmailGetRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authVerifyEmailGet(requestParameters.token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Activates user account in Postgres and Keycloak
     * @summary Verify email address via token payload
     * @param {AuthApiAuthVerifyEmailPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authVerifyEmailPost(requestParameters: AuthApiAuthVerifyEmailPostRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authVerifyEmailPost(requestParameters.authVerifyEmailPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

